feagi/feagi

- GENOME.md
- I think we discussed moving the Sphinx API doc stuff down a level in the `docs` directory and then moving other docs (GENOME, DEPLOY) into `docs` top level  <-- should I include in this PR?
- closes #9
> Draft of the genome development doc

- requirements.txt
- src/feagi_configuration.ini
- src/ipu/fcl_injector.py
- src/ipu/ipu_controller.py
- src/ipu/source/folder_monitor.py
- src/npu/burst_engine.py
- src/npu/comprehension.py
- Updated Watchdog version
- Removed unnecessary logging
- Fixed issue with folder monitor injecting text to FCL
- Improved log details and aestetics
> Logging improvements

- docker/Dockerfile
- src/evo/neuroembryogenesis.py
- src/feagi_configuration.ini
- src/inf/db_handler.py
- src/inf/initialize.py
- src/main.py
- src/npu/burst_engine.py
- Adopted InfluxDB 2.0 support
- Misc bug fixes
> Feature influxdb

- docker/Dockerfile
- docker/base.Dockerfile
- requirements.txt
- src/inf/initialize.py
- Changed feagi-base docker container from Alpine to Buster
- Added back the cpu and mem detection
> Moved from Alpine to Buster

- docker/Dockerfile
- docker/docker-compose-feagi-micro_ros-no_db.yml
- updating container config to what was used on the pi to successfully connect to the sonar sensor
> update compose .yml to get sonar working in container

- third_party/gazebo/smart_car/Dockerfile
- third_party/gazebo/smart_car/freenove_4wd_car_description/launch/freenove_smart_car.launch.py
- third_party/gazebo/smart_car/freenove_4wd_car_description/models/sdf/freenove_smart_car.sdf
- third_party/gazebo/smart_car/start_controller.sh
Added the battery on the robot. 
The launch file is also modified to convert the batterystate to ros2 and ros2 can share the full data now.
> Feature add battery in the robot on gazebo

- docker/docker-compose-feagi-ros-ign-VNC.yml
- third_party/gazebo/smart_car/freenove_4wd_car_description/models/sdf/freenove_smart_car.sdf
Placed the ultrasonic to the correct position.
Also I removed the unused volumes: in the yml file.
> Hotfix on ultrasonic and removed unused volume in docker-compose yml file

- DEPLOY.md
Added the demo section in deploy.md to secure the connection
> Doc tweak readme and deploy.md feagi core

- docker/Dockerfile
> remove the checkout

- third_party/grafana/dashboards/test_dashboard.json
- fixes a bad query in the example/test dashboard panel
- also removes an unused dashboard panel
> fix bad query in grafana dashboard config

- src/inf/initialize.py
- src/main.py
- minor changes to functions setting up the file paths for storing data
- need to refactor `init_working_directory` function to have less repetition/redundancy
> enable windows support

- third_party/gazebo/smart_car/freenove_4wd_car_description/README.md
* Added the collapsible list
* Enhanced the look
> Added the collapsible list

- third_party/godot/container/camera.gd
- third_party/godot/container/feagi.gd
- third_party/godot/container/project.godot
- third_party/godot/container/shape_test.tscn
- Changed the start camera position
- Added axis indicator 
- Changed the textbox to transparent
- Added a new object (gridmap3) for axis indicator
> Feature add arrow ingodot

- docker/feagi_apple_silicone.yml
> Update M1's YML

- requirements.txt
- src/feagi_configuration.ini
- src/mem/memory.py
- Removed plasticity printouts 
- Removed Launch from the requirements.txt
- Turned off voxel logging from FEAGI logs by default
> Misc cleanup

- src/api/api.py
- src/gui/src/App.js
- src/gui/src/routes/MonitoringDashboard.js
- src/gui/src/services/FeagiAPI.js
- src/trn/shock.py
- Added GUI menu option to enable/disable shock scenarios
> Shock Administration

- third_party/gazebo/smart_car/freenove_4wd_car_description/src/configuration.py
> updated power

- src/gui/src/routes/GenomeMode.js
- src/gui/src/routes/MonitoringDashboard.js
- Shock rename
- Genome mode tile rearrangement
> Minor UI Updates

- third_party/gazebo/smart_car/freenove_4wd_car_description/src/configuration.py
- third_party/gazebo/smart_car/freenove_4wd_car_description/src/controller.py
- Added threshold to work with IR. 25 is the default number
> Added threshold on config

- third_party/gazebo/smart_car/start_controller.sh
- Fixed this issue
- Implemented to make the screen as a full screen permanently
- Implemented to stay full screen without being toggle at al
l
> The random non-full screen issue

- src/evo/defaults/static_genome.py
- Replaced from `100` to `10000` to reduce the confusion for new users
> tweaked the max_age

- third_party/gazebo/smart_car/freenove_4wd_car_description/models/sdf/free_world.sdf
- third_party/gazebo/smart_car/freenove_4wd_car_description/models/sdf/smart_car.sdf
- third_party/godot/src/bridge_godot_python.py
- Improve IRs
- Improved physics in world
- Improved visual using IR
- Fixed the duplicated data in csv
- Improved performance in docker without lags (This issue occurs on non-M1 computers only) 
- Disabled shadows
> Hotfix fix ir and godot

- third_party/gazebo/smart_car/freenove_4wd_car_description/models/sdf/free_world.sdf
- third_party/gazebo/smart_car/freenove_4wd_car_description/models/sdf/new_ground.sdf
hot fix on new ground and original ground
> hotfix on the setting of the ground

- src/gui/src/routes/DefaultRobots.js
- src/gui/src/routes/MonitoringDashboard.js
- Ability to change the environment in main FEAGI view
- Ability to change the robot in main FEAGI view
> Robot and Environment change option during runtime

- docker/feagi.yml
- docker/feagi_apple_silicone.yml
- Added path to make it easier for anyone who wants to update the map/robot
> added home path to make it easier for anyone to change the robot/map

- third_party/gazebo/feagi_robot/src/controller.py
- Added feature where you can control the offset camera on GUI.
See the example below:
https://www.youtube.com/watch?v=h-yra2-bHZE
> added GUI camera control feature

- src/pns/stimuli_processor.py
- third_party/gazebo/simulation/robots/smart_car/smart_car.sdf
- third_party/gazebo/simulation/src/configuration.py
- third_party/gazebo/simulation/src/retina.py
- third_party/gazebo/simulation/src/robot.py
- third_party/physical_robots/freenove/smart_car/configuration.py
- third_party/physical_robots/freenove/smart_car/freenove_SmartCar.py
- third_party/physical_robots/freenove/smart_car/retina.py
- third_party/physical_robots/tello/tello.py
- third_party/psychopy/configuration.py
- third_party/psychopy/psychoPy.py
- third_party/psychopy/retina.py
Update:
1) Updated function to collect data accordingly and keep it standard for all
2) Added capabilities dict on config
3) Updated psychopy file to latest
> Feature update psychopy

- third_party/gazebo/simulation/Dockerfile
- third_party/gazebo/simulation/Dockerfile.M1
- Added cv2 for Retina.py on docker
> added cv2 for retina

- src/evo/genome_properties.py
- src/evo/genome_validator.py
- src/inf/initialize.py
- Genome syntax validation during load time
> Genome Validation

- third_party/gazebo/simulation/launch/robot.launch.py
- Added address path to convert between gazebo and ros2 to communicate with FEAGI
> fixed the launch setting to allow drone communicate with ros2

- src/evo/x_genesis.py
Fixed issue where adding a new cortical area using API was causing an exception.
> Bug: Cortical area addition

- docker/feagi.yml
- src/api/api.py
- src/inf/db_handler.py
- src/inf/initialize.py
- Added API to test InfluxDb availability
- Added dependencies to docker-compose feagi.yml
- fixed misc influx issues
> influxdb initialization

- src/api/api.py
- src/api/config.py
- src/npu/burst_engine.py
- src/npu/physiology.py
- CORS update
- Neuron leak fix
> Misc fixes

- src/api/api.py
- src/api/config.py
- src/npu/burst_engine.py
- src/npu/physiology.py
- Membrane potential logging update
> Bug: Membrane potential handling

- third_party/physical_robots/freenove/smart_car/configuration.py
- third_party/physical_robots/freenove/smart_car/freenove_SmartCar.py
- Updated to work with new feagi
> updated freenove to work with new feagi

- third_party/physical_robots/tello/configuration.py
- third_party/physical_robots/tello/tello.py
- Updated to work with new feagi
> updated to work with new feagi

- src/api/api.py
- src/api/config.py
- src/evo/genome_processor.py
- src/evo/neuron.py
- src/inf/initialize.py
- src/npu/burst_engine.py
- src/npu/physiology.py
- Fix for leak variability gene not working
> Bug: Leak variability not working

- third_party/physical_robots/mycobot/cobot_arm/src/configuration.py
- third_party/physical_robots/mycobot/cobot_arm/src/mycobot.py
- Update mycobot to work with latest FEAGI
> updated to work with latest feagi

- src/evo/circuits/leak_test_1:23.json
> test leak (#207)

- docker/feagi_apple_silicone.yml
- third_party/gazebo/simulation/Dockerfile.M1
- third_party/godot/godot_source/project.godot
- Tweak to support M2
- Hotfix for timer_api.gd
> Feature m2 support

- peripherals/feagi_agent_core/README.md
- peripherals/feagi_agent_freenove/README.md
- peripherals/feagi_agent_mycobot/LICENSE
- peripherals/feagi_agent_mycobot/README.md
- peripherals/feagi_agent_mycobot/feagi_agent_mycobot/CMakeLists.txt
- peripherals/feagi_agent_mycobot/feagi_agent_mycobot/__main__.py
- peripherals/feagi_agent_mycobot/feagi_agent_mycobot/package.xml
- peripherals/feagi_agent_mycobot/feagi_agent_mycobot/setup.cfg
- peripherals/feagi_agent_mycobot/feagi_agent_mycobot/setup.py
- peripherals/feagi_agent_mycobot/feagi_agent_mycobot/src/configuration.py
- peripherals/feagi_agent_mycobot/feagi_agent_mycobot/src/mycobot.py
- peripherals/feagi_agent_mycobot/feagi_agent_mycobot/start_mycobot.sh
- peripherals/feagi_agent_mycobot/pyproject.toml
- peripherals/feagi_agent_mycobot/refresh_for_upload.sh
- peripherals/feagi_agent_mycobot/setup.cfg
- peripherals/feagi_agent_webcam/README.md
- third_party/physical_robots/mycobot/cobot_arm/src/mycobot.py
- Updated readme
- Updated mycobot to work with feagi_agent_mycobot (Linux only currently)
- Added feagi_agent_mycobot
> Feature mycobot updated

- docker/feagi_apple_silicone.yml
- third_party/gazebo/simulation/src/robot.py
- third_party/godot/godot_source/feagi.gd
- third_party/godot/godot_source/menu_assets/burst_value.gd
- Updated M1's yml
- Updated needed line for gazebo python
- Fixed the annoying bug on refresh rate textbox
- Added the feature where a user move mouse out of that textbox while it's empty, it will rollback to '0'
> Feature update m1 yml

- third_party/gazebo/simulation/src/configuration.py
- third_party/gazebo/simulation/src/robot.py
- Clean up on Gazebo registration with FEAGI
- Remove extra space between command and comma in config
> Feature cleanup gazebo

- peripherals/feagi_agent_webcam/feagi_agent_webcam/__main__.py
- peripherals/feagi_agent_webcam/feagi_agent_webcam/configuration.py
- peripherals/feagi_agent_webcam/feagi_agent_webcam/controller.py
- peripherals/feagi_agent_webcam/setup.cfg
- Improve feagi agent webcam
- Added more flags
- Added video flag along with loop enable
- Improve ip flag. If not using it, default to localhost
- adjusted in configuration
- pip updated
> Feature webcam agent 0 0 3

- docker/feagi-OnlyGodot.yml
test - adding lighter docker compose file of only Feagi and Godot
> Add even lighter docker compose stack

- peripherals/feagi_agent_core/feagi_agent/retina.py
- peripherals/feagi_agent_core/setup.cfg
> update feagi_agent to 0.0.30

- src/evo/static_genome.json
- src/evo/synapse.py
- src/evo/synaptogenesis_rules.py
- src/evo/x_genesis.py
- Implementation of a new morphology allowing for one cortical area to project evenly into another.
> Projector Morphology

- docker/feagi_apple_silicone.yml
- Updated feagi_apple from feagi.yml's fix
> updated ports from feagi.yml

- peripherals/feagi_agent_freenove/setup.cfg
- peripherals/feagi_agent_mycobot/setup.cfg
- peripherals/feagi_agent_webcam/setup.cfg
> updated version

- src/api/api.py
- src/evo/static_genome.json
- src/evo/synapse.py
- src/evo/synaptogenesis_rules.py
- src/evo/voxels.py
- src/evo/x_genesis.py
- src/inf/initialize.py
- Ability to create morphologies based on a subset of neurons from the source cortical area
> Composite Morphology

- src/npu/burst_engine.py
- src/npu/physiology.py
- Fixed leaking behavior of neurons
> Neuron Leak Fix

- src/evo/defaults/genome/static_genome.json
- src/evo/genome_processor.py
- src/evo/genome_validator.py
- src/evo/static_genome.json
- src/inf/runtime_data.py
- src/npu/burst_engine.py
- Ability to detect morphology issues
- Genome validity indicator
> Genome Validator

- src/api/api.py
Cortical Map API
Cortical Name Mapping-Table API
Status API
> API improvements

- third_party/godot/godot_source/Cortical_area.gd
- Added 2 more things that it was overlooked last time
> updated the z to keep up with the list

- src/api/api.py
- src/evo/genome_validator.py
- src/evo/neuron.py
- src/evo/static_genome.json
- src/evo/synapse.py
- src/evo/x_genesis.py
- src/inf/initialize.py
- src/inf/runtime_data.py
- src/mem/memory.py
- src/npu/burst_engine.py
- src/npu/physiology.py
- An improved approach to neuroplasticity
- New neuron_id schema
> Neuroplasticity Refactor

- src/evo/synapse.py
- src/mem/memory.py
> Cortical Mapping API  Bug Fix

- third_party/godot/godot_source/Language/LEFTBAR_L.JSON
- third_party/godot/godot_source/UI/Units/Common_SubComponents/Button_SubComponent.gd
- third_party/godot/godot_source/UI/Units/Components/Button/Button.md
- third_party/godot/godot_source/UI/Units/Components/Button/Button_Component.gd
- third_party/godot/godot_source/UI/Units/Components/Button/button.tscn
- third_party/godot/godot_source/UI/Units/Components/Counter/Counter_Component.gd
- third_party/godot/godot_source/UI/Units/Components/DropDown/DropDown_Component.gd
- third_party/godot/godot_source/UI/Units/Components/Field/Field_Component.gd
- third_party/godot/godot_source/UI/Units/Components/Toggle/Toggle_Component.gd
- third_party/godot/godot_source/UI/Units/Unit.gd
- third_party/godot/godot_source/UI_Structures/LEFTBAR.JSON
> Unit buttons

- third_party/godot/godot_source/HTML/Dockerfile
- third_party/godot/godot_source/HTML/nodegraph.yml
> Hotfix port godot4

- third_party/godot/godot_source/Shared_components/HelperFuncs.gd
- third_party/godot/godot_source/UI/Units/Common_SubComponents/Button_SubComponent.gd
- third_party/godot/godot_source/UI/Units/Components/Button/Button_Component.gd
- third_party/godot/godot_source/UI/Units/Components/Fill/Fill_Component.gd
- third_party/godot/godot_source/UI/Units/Components/Fill/Fill_SubComponent.gd
- third_party/godot/godot_source/UI/Units/Components/Fill/fill.tscn
- third_party/godot/godot_source/UI/Units/Components/Header/Header_Component.gd
- third_party/godot/godot_source/UI/Units/Unit.gd
- third_party/godot/godot_source/UI/Units/unit.tscn
- third_party/godot/godot_source/UI_Structures/TOPBAR.JSON
Added blank component with color support
> Blank component

- third_party/godot/godot_source/UI/Newnit/Containers/Newnit_Scroll.gd
- third_party/godot/godot_source/UI/Newnit/PreloadScripts/Container_Core.gd
add scroll bar support (duplicate coming)
> Scroll bar

- third_party/godot/godot_source/UI/Newnit/Containers/Newnit_Box.gd
- third_party/godot/godot_source/UI/Newnit/Containers/Newnit_Collapsible.gd
- third_party/godot/godot_source/UI/Newnit/Containers/Newnit_Popup.gd
- third_party/godot/godot_source/UI/Newnit/Containers/Newnit_Scroll.gd
- third_party/godot/godot_source/UI/Newnit/Containers/Newnit_SubList.gd
- third_party/godot/godot_source/UI/Newnit/Containers/Newnit_Tabs.gd
- third_party/godot/godot_source/UI/Newnit/Elements/Elements/Element_Base.gd
- third_party/godot/godot_source/UI/Newnit/Elements/Elements/Element_TextBox.gd
- third_party/godot/godot_source/UI/Newnit/Elements/Sub_Elements/TextEdit_Sub.gd
- third_party/godot/godot_source/UI/Newnit/PreloadScripts/Container_Core.gd
- third_party/godot/godot_source/UI/Newnit/PreloadScripts/Newnit_core.gd
- third_party/godot/godot_source/UI_Structures/MANAGE_MORPHOLOGY.JSON
> Feature textedit

- peripherals/feagi_agent_freenove/feagi_agent_freenove/__main__.py
- peripherals/feagi_agent_freenove/feagi_agent_freenove/configuration.py
- peripherals/feagi_agent_freenove/feagi_agent_freenove/controller.py
- peripherals/feagi_agent_mycobot/feagi_agent_mycobot/src/configuration.py
- peripherals/feagi_agent_mycobot/feagi_agent_mycobot/src/mycobot.py
- peripherals/feagi_agent_webcam/feagi_agent_webcam/controller.py
- third_party/gazebo/simulation/src/configuration.py
- third_party/gazebo/simulation/src/robot.py
- third_party/physical_robots/elecfreaks/javascript/configuration.py
- third_party/physical_robots/elecfreaks/javascript/controller.py
- third_party/physical_robots/tello/configuration.py
- third_party/physical_robots/tello/tello.py
> Feature update controllers

- docker/feagi.yml
- tests/test_initialization.py
- third_party/gazebo/simulation/src/configuration.py
- Enabled gazebo
- Fixed Gazebo's port
> Feature updated feagidotyml

- requirements.txt
- third_party/godot/src/bridge_godot_python.py
- third_party/godot/src/configuration.py
- Updated bridge
- Fixed the issue where bridge unable to connect feagi after waiting for at least 20 seconds
- Restructured the code a little
- Use TCP to check the connectivity instead of http requests.
> Feature upgrade bridge

- .github/workflows/versions_update.yml
> added workflow dispatch

- .github/workflows/microbit_version_update.yml
- .github/workflows/versions_to_pr.yml
- Tweeaked title for microbit
- Updated to work with PR
> Feature tweakymls

- .github/workflows/contribute_to_public_feagi.yml
- src/evo/genome_processor.py
This PR syncs with latest Neuraville Inc. development code.
> Updates from Neuraville Inc

- .github/workflows/push_to_PyPi_feagi_agent.yml
- .github/workflows/push_to_PyPi_freenove.yml
- .github/workflows/push_to_PyPi_mycobot.yml
- .github/workflows/push_to_PyPi_video_capture.yml
> Feature fix pypi ymls

- .github/workflows/docker-image-javascript-webcam.yml
- .github/workflows/docker-image-microbit.yml
- .github/workflows/push_to_PyPi_freenove.yml
- push latest changes on microbit and webcam
> Hotfix missingymls

- community_genomes/LearningV1.1B/Original Genome.json
Includes the .json file for our original x/y stimulation decoder genome
> Added Original Genome.json

- community_genomes/Webots-salamander/README.md
- community_genomes/Webots-salamander/webots-salamander-AvoidWalls.json
Salamandar walks foreword until it gets close to an obstacle. Before hitting, it turns to avoid the obstacle.
> added Webots salamander genome

- community_genomes/FeagiMobileAppGenomes/BenGradeckGenome.json
- community_genomes/FeagiMobileAppGenomes/README.md
This is me addding files related to a group genome and readme.
> Adding Files for my personal genome

- community_genomes/GazeboParser-Lukas/README.md
- community_genomes/GazeboParser-Lukas/feagi_genome_gazebo_parser_demo_-_lukas.json
> Lukas Finn Genome - Gazebo Parsing Team

- community_genomes/Blender/feagi_blender_keyframe_genome.json
Blender Genome used for testing keyframes.
> Added Blender Genome
